Repository OCA/helpdesk, pull requests merged in 2020-05, with the labels that each got.

#122 [FIX] Repeated active field failure in the helpdesk team view
  helpdesk_mgmt/views/helpdesk_ticket_team_view.xml
Labels: approved, bot is merging ⏳

#117 [MIG] helpdesk_mgmt: Migration to 13.0
  .isort.cfg
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/__init__.py
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/controllers/__init__.py
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/demo/helpdesk_demo.xml
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/i18n/pt_BR.po
  helpdesk_mgmt/models/__init__.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_category.py
  helpdesk_mgmt/models/helpdesk_ticket_channel.py
  helpdesk_mgmt/models/helpdesk_ticket_stage.py
  helpdesk_mgmt/models/helpdesk_ticket_tag.py
  helpdesk_mgmt/models/helpdesk_ticket_team.py
  helpdesk_mgmt/models/res_partner.py
  helpdesk_mgmt/readme/CONFIGURE.rst
  helpdesk_mgmt/readme/CONTRIBUTORS.rst
  helpdesk_mgmt/readme/DESCRIPTION.rst
  helpdesk_mgmt/readme/USAGE.rst
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/security/ir.model.access.csv
  helpdesk_mgmt/static/description/Categories.PNG
  helpdesk_mgmt/static/description/Channels.PNG
  helpdesk_mgmt/static/description/Stage.PNG
  helpdesk_mgmt/static/description/Tags.PNG
  helpdesk_mgmt/static/description/Teams.PNG
  helpdesk_mgmt/static/description/Tickets01.PNG
  helpdesk_mgmt/static/description/Tickets02.PNG
  helpdesk_mgmt/static/description/Tickets03.PNG
  helpdesk_mgmt/static/description/Tickets_Kanban.PNG
  helpdesk_mgmt/static/description/helpdesk.svg
  helpdesk_mgmt/static/description/icon.png
  helpdesk_mgmt/static/description/index.html
  helpdesk_mgmt/tests/__init__.py
  helpdesk_mgmt/tests/test_helpdesk_ticket.py
  helpdesk_mgmt/tests/test_helpdesk_ticket_team.py
  helpdesk_mgmt/tests/test_res_partner.py
  helpdesk_mgmt/views/helpdesk_dashboard_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_menu.xml
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_tag_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_team_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
  helpdesk_mgmt/views/res_partner_views.xml
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/helpdesk_mgmt/odoo/addons/helpdesk_mgmt
  setup/helpdesk_mgmt/setup.py
Labels: bot is merging ⏳

#126 [IMP] Add Archive Smart Button on Tickets
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_view.xml
Labels: approved, bot is merging ⏳, ready to merge
