Repository OCA/helpdesk, pull requests merged in 2020-06, with the labels that each got.

#134 [12.0][FIX] Use HTML field type for descriptions, to match widgets
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/migrations/12.0.1.14.1/post-migrate.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_stage.py
Labels: bot is merging ⏳

#135 [11.0][FIX] Use HTML field type for descriptions, to match widgets
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/migrations/11.0.1.10.1/post-migrate.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_stage.py
Labels: bot is merging ⏳

#136 [13.0][FIX] Use HTML field type for descriptions, to match widgets
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/migrations/13.0.1.0.1/post-migrate.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_stage.py
Labels: bot is merging ⏳

#139 [FIX] helpdesk_mgmt: add write permission for portal user
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#69 11.0 add searchbar input
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
Labels: approved, bot is merging ⏳

#140 [FIX] helpdesk_mgmt: fix error when submitting a ticket with an attachment
  helpdesk_mgmt/controllers/main.py
Labels: approved, bot is merging ⏳

#130 [MIG] helpdesk_motive: Migration to 13.0
  helpdesk_motive/README.rst
  helpdesk_motive/__init__.py
  helpdesk_motive/__manifest__.py
  helpdesk_motive/i18n/es.po
  helpdesk_motive/i18n/helpdesk_motive.pot
  helpdesk_motive/i18n/pt_BR.po
  helpdesk_motive/models/__init__.py
  helpdesk_motive/models/helpdesk_ticket.py
  helpdesk_motive/models/helpdesk_ticket_motive.py
  helpdesk_motive/readme/CONFIGURE.rst
  helpdesk_motive/readme/CONTRIBUTORS.rst
  helpdesk_motive/readme/DESCRIPTION.rst
  helpdesk_motive/readme/USAGE.rst
  helpdesk_motive/security/ir.model.access.csv
  helpdesk_motive/static/description/icon.png
  helpdesk_motive/static/description/index.html
  helpdesk_motive/views/helpdesk_ticket.xml
  helpdesk_motive/views/helpdesk_ticket_motive.xml
  setup/helpdesk_motive/odoo/addons/helpdesk_motive
  setup/helpdesk_motive/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#131 13.0 mig helpdesk type
  helpdesk_type/README.rst
  helpdesk_type/__init__.py
  helpdesk_type/__manifest__.py
  helpdesk_type/i18n/es.po
  helpdesk_type/i18n/helpdesk_type.pot
  helpdesk_type/i18n/pt_BR.po
  helpdesk_type/models/__init__.py
  helpdesk_type/models/helpdesk_ticket.py
  helpdesk_type/models/helpdesk_ticket_team.py
  helpdesk_type/models/helpdesk_ticket_type.py
  helpdesk_type/readme/CONFIGURE.rst
  helpdesk_type/readme/CONTRIBUTORS.rst
  helpdesk_type/readme/DESCRIPTION.rst
  helpdesk_type/readme/USAGE.rst
  helpdesk_type/security/ir.model.access.csv
  helpdesk_type/static/description/icon.png
  helpdesk_type/static/description/index.html
  helpdesk_type/views/helpdesk_ticket.xml
  helpdesk_type/views/helpdesk_ticket_team.xml
  helpdesk_type/views/helpdesk_ticket_type.xml
  setup/helpdesk_type/odoo/addons/helpdesk_type
  setup/helpdesk_type/setup.py
Labels: approved, bot is merging ⏳, ready to merge
