Repository OCA/helpdesk, pull requests merged in 2020-08, with the labels that each got.

#152 [12.0][FIX] helpdesk_mgmt_project: missing context for task creation
  helpdesk_mgmt_project/views/helpdesk_ticket_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#154 [13.0][MIG] helpdesk_mgmt_project
  helpdesk_mgmt_project/README.rst
  helpdesk_mgmt_project/__init__.py
  helpdesk_mgmt_project/__manifest__.py
  helpdesk_mgmt_project/i18n/es.po
  helpdesk_mgmt_project/i18n/es_AR.po
  helpdesk_mgmt_project/i18n/fr.po
  helpdesk_mgmt_project/i18n/helpdesk_mgmt_project.pot
  helpdesk_mgmt_project/i18n/it.po
  helpdesk_mgmt_project/i18n/pt.po
  helpdesk_mgmt_project/models/__init__.py
  helpdesk_mgmt_project/models/helpdesk_ticket.py
  helpdesk_mgmt_project/models/project.py
  helpdesk_mgmt_project/models/project_task.py
  helpdesk_mgmt_project/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_project/readme/DESCRIPTION.rst
  helpdesk_mgmt_project/static/description/icon.png
  helpdesk_mgmt_project/static/description/index.html
  helpdesk_mgmt_project/tests/__init__.py
  helpdesk_mgmt_project/tests/test_helpdesk_ticket.py
  helpdesk_mgmt_project/views/helpdesk_ticket_view.xml
  helpdesk_mgmt_project/views/project_task_view.xml
  helpdesk_mgmt_project/views/project_view.xml
  setup/helpdesk_mgmt_project/odoo/addons/helpdesk_mgmt_project
  setup/helpdesk_mgmt_project/setup.py
Labels: approved, bot is merging ⏳

#155 [13.0][MIG] helpdesk_mgmt_timesheet
  helpdesk_mgmt_timesheet/README.rst
  helpdesk_mgmt_timesheet/__init__.py
  helpdesk_mgmt_timesheet/__manifest__.py
  helpdesk_mgmt_timesheet/demo/helpdesk_mgmt_timesheet_demo.xml
  helpdesk_mgmt_timesheet/i18n/es.po
  helpdesk_mgmt_timesheet/i18n/helpdesk_mgmt_timesheet.pot
  helpdesk_mgmt_timesheet/models/__init__.py
  helpdesk_mgmt_timesheet/models/helpdesk_ticket.py
  helpdesk_mgmt_timesheet/models/helpdesk_ticket_team.py
  helpdesk_mgmt_timesheet/models/hr_timesheet.py
  helpdesk_mgmt_timesheet/readme/CONFIGURE.rst
  helpdesk_mgmt_timesheet/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_timesheet/readme/DESCRIPTION.rst
  helpdesk_mgmt_timesheet/readme/USAGE.rst
  helpdesk_mgmt_timesheet/report/report_timesheet_templates.xml
  helpdesk_mgmt_timesheet/static/description/icon.png
  helpdesk_mgmt_timesheet/static/description/index.html
  helpdesk_mgmt_timesheet/tests/__init__.py
  helpdesk_mgmt_timesheet/tests/test_helpdesk_mgmt_timesheet.py
  helpdesk_mgmt_timesheet/views/helpdesk_team_view.xml
  helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
  helpdesk_mgmt_timesheet/views/hr_timesheet_view.xml
  setup/helpdesk_mgmt_timesheet/odoo/addons/helpdesk_mgmt_timesheet
  setup/helpdesk_mgmt_timesheet/setup.py
Labels: approved, bot is merging ⏳

#149 [12.0][IMP] readme.rst: Add addons table and translate status
  README.md
Labels: approved, bot is merging ⏳, ready to merge

#150 [13.0][IMP] readme.rst: Add addons table and translate status
  README.md
Labels: approved, bot is merging ⏳, ready to merge

#103 [11.0][FIX] - helpdesk_mgmt
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_view.xml
Labels: bot is merging ⏳
