Repository OCA/helpdesk, pull requests merged in 2020-10, with the labels that each got.

#142 [12.0][ADD] helpdesk mgmt fieldservice
  .gitignore
  helpdesk_mgmt_fieldservice/README.rst
  helpdesk_mgmt_fieldservice/__init__.py
  helpdesk_mgmt_fieldservice/__manifest__.py
  helpdesk_mgmt_fieldservice/i18n/helpdesk_mgmt_fieldservice.pot
  helpdesk_mgmt_fieldservice/i18n/pt_BR.po
  helpdesk_mgmt_fieldservice/models/__init__.py
  helpdesk_mgmt_fieldservice/models/fsm_location.py
  helpdesk_mgmt_fieldservice/models/fsm_order.py
  helpdesk_mgmt_fieldservice/models/helpdesk_ticket.py
  helpdesk_mgmt_fieldservice/readme/CONFIGURE.rst
  helpdesk_mgmt_fieldservice/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_fieldservice/readme/DESCRIPTION.rst
  helpdesk_mgmt_fieldservice/readme/HISTORY.rst
  helpdesk_mgmt_fieldservice/readme/INSTALL.rst
  helpdesk_mgmt_fieldservice/readme/ROADMAP.rst
  helpdesk_mgmt_fieldservice/readme/USAGE.rst
  helpdesk_mgmt_fieldservice/security/ir.model.access.csv
  helpdesk_mgmt_fieldservice/static/description/icon.png
  helpdesk_mgmt_fieldservice/static/description/index.html
  helpdesk_mgmt_fieldservice/static/src/scss/helpdesk_column.scss
  helpdesk_mgmt_fieldservice/views/fsm_location_views.xml
  helpdesk_mgmt_fieldservice/views/fsm_order_views.xml
  helpdesk_mgmt_fieldservice/views/helpdesk_ticket_views.xml
  helpdesk_mgmt_fieldservice/views/res_partner.xml
  helpdesk_mgmt_fieldservice/wizards/__init__.py
  helpdesk_mgmt_fieldservice/wizards/fsm_order_close_wizard.py
  helpdesk_mgmt_fieldservice/wizards/fsm_order_close_wizard.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#166 [11.0][MIG][helpdesk_type] Backport 12.0
  helpdesk_type/README.rst
  helpdesk_type/__init__.py
  helpdesk_type/__manifest__.py
  helpdesk_type/i18n/es.po
  helpdesk_type/i18n/es_AR.po
  helpdesk_type/i18n/it.po
  helpdesk_type/i18n/pt.po
  helpdesk_type/i18n/pt_BR.po
  helpdesk_type/models/__init__.py
  helpdesk_type/models/helpdesk_ticket.py
  helpdesk_type/models/helpdesk_ticket_team.py
  helpdesk_type/models/helpdesk_ticket_type.py
  helpdesk_type/readme/CONFIGURE.rst
  helpdesk_type/readme/CONTRIBUTORS.rst
  helpdesk_type/readme/DESCRIPTION.rst
  helpdesk_type/readme/USAGE.rst
  helpdesk_type/security/ir.model.access.csv
  helpdesk_type/static/description/icon.png
  helpdesk_type/static/description/index.html
  helpdesk_type/views/helpdesk_ticket.xml
  helpdesk_type/views/helpdesk_ticket_team.xml
  helpdesk_type/views/helpdesk_ticket_type.xml
Labels: bot is merging ⏳

#144 [12.0] Improve helpdesk_mgmt
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/models/__init__.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_stage.py
  helpdesk_mgmt/models/ir_attachment.py
  helpdesk_mgmt/readme/CONTRIBUTORS.rst
  helpdesk_mgmt/tests/test_helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_stage_view.xml
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
  helpdesk_mgmt/views/helpdesk_ticket_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#172 [FIX] Helpdesk Management Timesheet
  helpdesk_mgmt_timesheet/models/hr_timesheet.py
Labels: approved, bot is merging ⏳
