Repository OCA/helpdesk, pull requests merged in 2021-03, with the labels that each got.

#185 [12.0] [ADD] helpdesk_mgmt_partner_sequence
  helpdesk_mgmt_partner_sequence/README.rst
  helpdesk_mgmt_partner_sequence/__init__.py
  helpdesk_mgmt_partner_sequence/__manifest__.py
  helpdesk_mgmt_partner_sequence/demo/helpdesk_demo.xml
  helpdesk_mgmt_partner_sequence/models/__init__.py
  helpdesk_mgmt_partner_sequence/models/helpdesk_ticket.py
  helpdesk_mgmt_partner_sequence/models/res_partner.py
  helpdesk_mgmt_partner_sequence/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_partner_sequence/readme/DESCRIPTION.rst
  helpdesk_mgmt_partner_sequence/static/description/index.html
  helpdesk_mgmt_partner_sequence/tests/__init__.py
  helpdesk_mgmt_partner_sequence/tests/test_helpdesk_ticket.py
  helpdesk_mgmt_partner_sequence/views/res_partner_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#203 [12.0][IMP] helpdesk_type: added grouping tickets by type & some demo data
  helpdesk_type/README.rst
  helpdesk_type/__manifest__.py
  helpdesk_type/demo/helpdesk_type_demo.xml
  helpdesk_type/readme/CONTRIBUTORS.rst
  helpdesk_type/static/description/index.html
  helpdesk_type/views/helpdesk_ticket.xml
Labels: approved, bot is merging ⏳, ready to merge

#204 [12.0][FIX] fixed xml id in fsm_location.py
  helpdesk_mgmt_fieldservice/models/fsm_location.py
Labels: approved, bot is merging ⏳, ready to merge

#184 [12.0][FIX] allow to submit a ticket to all internal & portal users
  helpdesk_mgmt/readme/CONTRIBUTORS.rst
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳

#178 [FIX] helpdesk_mgmt: fix the following traceback
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: bot is merging ⏳
