Repository OCA/helpdesk, pull requests merged in 2021-04, with the labels that each got.

#216 [13.0][fix] Rules on who can access to tickets from the Portal should only be governed by the ir.rules.
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/security/helpdesk_security.xml
Labels: approved, bot is merging ⏳

#217 [12.0][fix] Rules on who can access to tickets from the Portal
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/demo/helpdesk_demo.xml
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt_project/i18n/it.po
Labels: approved, bot is merging ⏳

#219 [13.0][MIG] helpdesk_mgmt: add migration script for external ID renaming
  helpdesk_mgmt/migrations/13.0.1.2.3/pre-migrate.py
Labels: approved

#221 [12.0][MIG] helpdesk_mgmt: add migration script for external ID renaming
  helpdesk_mgmt/migrations/12.0.1.23.1/pre-migrate.py
Labels: approved

#223 [helpdesk_type][fix] only reset team and user when the new type does not match
  helpdesk_type/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#206 [13.0][IMP] helpdesk_mgmt_timesheet: filter tickets with activity on timesheets today
  helpdesk_mgmt_timesheet/models/helpdesk_ticket.py
  helpdesk_mgmt_timesheet/tests/test_helpdesk_mgmt_timesheet.py
  helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
Labels: approved, bot is merging ⏳, ready to merge
