Repository OCA/helpdesk, pull requests merged in 2021-05, with the labels that each got.

#225 [13.0][FIX]helpdesk_mgmt_timesheet: default_project not a field helpdesk.ticket.team
  helpdesk_mgmt_timesheet/models/helpdesk_ticket_team.py
Labels: approved, bot is merging ⏳

#237 [14.0][FIX] helpdesk_mgmt: wrong encoding for .po files
  helpdesk_mgmt/i18n/es_AR.po
  helpdesk_mgmt/i18n/pt_BR.po
Labels: bot is merging ⏳

#226 [14.0][FIX]helpdesk_mgmt: replace 'force_company' with 'with_company'
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#227 [14.0][MIG]helpdesk_mgmt_project, standard migration
  helpdesk_mgmt_project/README.rst
  helpdesk_mgmt_project/__init__.py
  helpdesk_mgmt_project/__manifest__.py
  helpdesk_mgmt_project/i18n/es.po
  helpdesk_mgmt_project/i18n/es_AR.po
  helpdesk_mgmt_project/i18n/fr.po
  helpdesk_mgmt_project/i18n/helpdesk_mgmt_project.pot
  helpdesk_mgmt_project/i18n/hu.po
  helpdesk_mgmt_project/i18n/it.po
  helpdesk_mgmt_project/i18n/pt.po
  helpdesk_mgmt_project/models/__init__.py
  helpdesk_mgmt_project/models/helpdesk_ticket.py
  helpdesk_mgmt_project/models/project.py
  helpdesk_mgmt_project/models/project_task.py
  helpdesk_mgmt_project/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_project/readme/DESCRIPTION.rst
  helpdesk_mgmt_project/static/description/icon.png
  helpdesk_mgmt_project/static/description/index.html
  helpdesk_mgmt_project/tests/__init__.py
  helpdesk_mgmt_project/tests/test_helpdesk_ticket.py
  helpdesk_mgmt_project/views/helpdesk_ticket_view.xml
  helpdesk_mgmt_project/views/project_task_view.xml
  helpdesk_mgmt_project/views/project_view.xml
  setup/helpdesk_mgmt_project/odoo/addons/helpdesk_mgmt_project
  setup/helpdesk_mgmt_project/setup.py
Labels: approved, bot is merging ⏳, ready to merge
