Repository OCA/helpdesk, pull requests merged in 2022-02, with the labels that each got.

#293 [13.0][ADD] helpdesk_mgmtsystem_nonconformity: New addon
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_tag_views.xml
  helpdesk_mgmtsystem_nonconformity/README.rst
  helpdesk_mgmtsystem_nonconformity/__init__.py
  helpdesk_mgmtsystem_nonconformity/__manifest__.py
  helpdesk_mgmtsystem_nonconformity/data/helpdesk_ticket_stage.xml
  helpdesk_mgmtsystem_nonconformity/i18n/es.po
  helpdesk_mgmtsystem_nonconformity/models/__init__.py
  helpdesk_mgmtsystem_nonconformity/models/helpdesk_ticket.py
  helpdesk_mgmtsystem_nonconformity/models/helpdesk_ticket_stage.py
  helpdesk_mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
  helpdesk_mgmtsystem_nonconformity/readme/CONTRIBUTORS.rst
  helpdesk_mgmtsystem_nonconformity/readme/DESCRIPTION.rst
  helpdesk_mgmtsystem_nonconformity/static/description/icon.png
  helpdesk_mgmtsystem_nonconformity/static/description/index.html
  helpdesk_mgmtsystem_nonconformity/tests/__init__.py
  helpdesk_mgmtsystem_nonconformity/tests/test_mgmtsystem_nonconformity.py
  helpdesk_mgmtsystem_nonconformity/views/helpdesk_ticket_stage_view.xml
  helpdesk_mgmtsystem_nonconformity/views/helpdesk_ticket_view.xml
  helpdesk_mgmtsystem_nonconformity/views/mgmtsystem_nonconformity_view.xml
  oca_dependencies.txt
  setup/helpdesk_mgmtsystem_nonconformity/odoo/addons/helpdesk_mgmtsystem_nonconformity
  setup/helpdesk_mgmtsystem_nonconformity/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#214 [12.0] helpdesk_mgmt: improve ticket display name and name search, with ticket number
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/tests/test_helpdesk_ticket.py
Labels: approved, ready to merge, bot is merging ⏳

#242 [11.0][ADD] module helpdesk_mgmt_solution
  helpdesk_mgmt_solution/README.rst
  helpdesk_mgmt_solution/__init__.py
  helpdesk_mgmt_solution/__manifest__.py
  helpdesk_mgmt_solution/demo/helpdesk_solution_demo.xml
  helpdesk_mgmt_solution/models/__init__.py
  helpdesk_mgmt_solution/models/helpdesk_solution.py
  helpdesk_mgmt_solution/models/helpdesk_ticket.py
  helpdesk_mgmt_solution/security/ir.model.access.csv
  helpdesk_mgmt_solution/tests/__init__.py
  helpdesk_mgmt_solution/tests/test_solution.py
  helpdesk_mgmt_solution/views/helpdesk_solution_view.xml
  helpdesk_mgmt_solution/views/helpdesk_ticket_view.xml
  helpdesk_mgmt_solution/views/menu_view.xml
  helpdesk_mgmt_solution/wizard/__init__.py
  helpdesk_mgmt_solution/wizard/solution.py
  helpdesk_mgmt_solution/wizard/solution.xml
Labels: approved, ready to merge, bot is merging ⏳

#157 [13.0][ADD] helpdesk_mgmt_sla 13.0.1.1.0
  helpdesk_mgmt_sla/README.rst
  helpdesk_mgmt_sla/__init__.py
  helpdesk_mgmt_sla/__manifest__.py
  helpdesk_mgmt_sla/data/helpdesk_sla_cron.xml
  helpdesk_mgmt_sla/demo/helpdesk_mgmt_sla_demo.xml
  helpdesk_mgmt_sla/i18n/es.po
  helpdesk_mgmt_sla/models/__init__.py
  helpdesk_mgmt_sla/models/helpdesk_sla.py
  helpdesk_mgmt_sla/models/helpdesk_ticket.py
  helpdesk_mgmt_sla/models/helpdesk_ticket_team.py
  helpdesk_mgmt_sla/readme/CONFIGURE.rst
  helpdesk_mgmt_sla/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_sla/readme/DESCRIPTION.rst
  helpdesk_mgmt_sla/readme/USAGE.rst
  helpdesk_mgmt_sla/security/ir.model.access.csv
  helpdesk_mgmt_sla/static/description/icon.png
  helpdesk_mgmt_sla/static/description/index.html
  helpdesk_mgmt_sla/tests/__init__.py
  helpdesk_mgmt_sla/tests/test_helpdesk_mgmt_sla.py
  helpdesk_mgmt_sla/views/helpdesk_sla_views.xml
  helpdesk_mgmt_sla/views/helpdesk_ticket_team_views.xml
  helpdesk_mgmt_sla/views/helpdesk_ticket_views.xml
  setup/helpdesk_mgmt_sla/odoo/addons/helpdesk_mgmt_sla
  setup/helpdesk_mgmt_sla/setup.py
Labels: bot is merging ⏳

#299 [13.0][IMP] helpdesk_mgmt: add full ticket name to customer view
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/migrations/13.0.1.7.0/pre-migrate.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳

#302 [14.0][IMP] helpdesk_mgmt: add full ticket name to customer view
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/migrations/14.0.1.4.0/pre-migration.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳

#303 [15.0][IMP] helpdesk_mgmt: add full ticket name to customer view
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/migrations/15.0.1.2.0/pre-migration.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: bot is merging ⏳

#301 [14.0][FIX] Avoid error when creating ticked from a duplicated customer
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳

#304 [15.0][FIX] Avoid error when creating ticked from a duplicated customer
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: bot is merging ⏳

#305 [14.0][FIX] helpdesk_mgmt: several forward ports
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/migrations/14.0.1.0.0/noupdate_changes.xml
  helpdesk_mgmt/migrations/14.0.1.0.0/post-migration.py
  helpdesk_mgmt/migrations/14.0.1.4.0/post-migration.py
  helpdesk_mgmt/migrations/14.0.1.5.1/noupdate_changes.xml
  helpdesk_mgmt/migrations/14.0.1.5.1/post-migration.py
  helpdesk_mgmt/migrations/14.0.1.5.1/pre-migrate.py
  helpdesk_mgmt/models/res_partner.py
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt_timesheet/tests/test_helpdesk_timesheet_time_control.py
Labels: bot is merging ⏳

#306 [13.0][FIX] helpdesk_mgmt: load noupdate_changes in template
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/migrations/13.0.1.7.0/post-migration.py
  helpdesk_mgmt/models/res_partner.py
  helpdesk_mgmt_timesheet_time_control/tests/test_helpdesk_timesheet_time_control.py
Labels: bot is merging ⏳

#307 [15.0][FIX] helpdesk_mgmt: several forward ports
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/migrations/15.0.1.2.0/post-migration.py
  helpdesk_mgmt/migrations/15.0.1.3.1/noupdate_changes.xml
  helpdesk_mgmt/migrations/15.0.1.3.1/post-migration.py
  helpdesk_mgmt/migrations/15.0.1.3.1/pre-migrate.py
  helpdesk_mgmt/models/res_partner.py
  helpdesk_mgmt/security/helpdesk_security.xml
Labels: bot is merging ⏳
