Repository OCA/helpdesk, pull requests merged in 2022-11, with the labels that each got.

#375 helpdesk_mgmt: Fix French translations
  helpdesk_mgmt/i18n/fr.po
Labels: bot is merging ⏳

#378 [IMP] helpdesk_mgmt: Test portal routes
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/tests/__init__.py
  helpdesk_mgmt/tests/test_portal.py
Labels: approved, ready to merge, bot is merging ⏳

#377 [IMP] helpdesk_mgmt: Modernize ticket portal views
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/tests/test_portal.py
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: bot is merging ⏳

#379 [15.0][FIX] helpdesk_mgmt: Preserve line breaks
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/tests/test_portal.py
Labels: approved, bot is merging ⏳

#387 [13.0][FIX] helpdesk_mgmt: Fix kanban ticket view
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
  helpdesk_mgmt_rating/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#389 [14.0][FIX] helpdesk_mgmt: Fix kanban ticket view
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
  helpdesk_mgmt_rating/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#391 [15.0][FIX] helpdesk_mgmt: Fix kanban ticket view
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳
