Repository OCA/helpdesk, pull requests merged in 2022-06, with the labels that each got.

#331 [14.0][FIX/IMP] helpdesk_mgmt: company logo in mail template + ticket order
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#316 [15.0][MIG] helpdesk_mgmt_project
  helpdesk_mgmt_project/README.rst
  helpdesk_mgmt_project/__init__.py
  helpdesk_mgmt_project/__manifest__.py
  helpdesk_mgmt_project/i18n/es.po
  helpdesk_mgmt_project/i18n/es_AR.po
  helpdesk_mgmt_project/i18n/fr.po
  helpdesk_mgmt_project/i18n/helpdesk_mgmt_project.pot
  helpdesk_mgmt_project/i18n/hu.po
  helpdesk_mgmt_project/i18n/it.po
  helpdesk_mgmt_project/i18n/pt.po
  helpdesk_mgmt_project/models/__init__.py
  helpdesk_mgmt_project/models/helpdesk_ticket.py
  helpdesk_mgmt_project/models/project.py
  helpdesk_mgmt_project/models/project_task.py
  helpdesk_mgmt_project/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_project/readme/DESCRIPTION.rst
  helpdesk_mgmt_project/static/description/icon.png
  helpdesk_mgmt_project/static/description/index.html
  helpdesk_mgmt_project/tests/__init__.py
  helpdesk_mgmt_project/tests/test_helpdesk_ticket.py
  helpdesk_mgmt_project/views/helpdesk_ticket_view.xml
  helpdesk_mgmt_project/views/project_task_view.xml
  helpdesk_mgmt_project/views/project_view.xml
  setup/helpdesk_mgmt_project/odoo/addons/helpdesk_mgmt_project
  setup/helpdesk_mgmt_project/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#333 [15.0][IMP] helpdesk_mgmt: ticket order
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: bot is merging ⏳

#332 [13.0][FIX/IMP] helpdesk_mgmt: company logo in mail template + ticket order
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: bot is merging ⏳

#325 [12.0][MIG] helpdesk_mgmt_sla
  helpdesk_mgmt_sla/README.rst
  helpdesk_mgmt_sla/__init__.py
  helpdesk_mgmt_sla/__manifest__.py
  helpdesk_mgmt_sla/data/helpdesk_sla_cron.xml
  helpdesk_mgmt_sla/demo/helpdesk_mgmt_sla_demo.xml
  helpdesk_mgmt_sla/i18n/es.po
  helpdesk_mgmt_sla/i18n/helpdesk_mgmt_sla.pot
  helpdesk_mgmt_sla/models/__init__.py
  helpdesk_mgmt_sla/models/helpdesk_sla.py
  helpdesk_mgmt_sla/models/helpdesk_ticket.py
  helpdesk_mgmt_sla/models/helpdesk_ticket_team.py
  helpdesk_mgmt_sla/readme/CONFIGURE.rst
  helpdesk_mgmt_sla/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_sla/readme/DESCRIPTION.rst
  helpdesk_mgmt_sla/readme/USAGE.rst
  helpdesk_mgmt_sla/security/ir.model.access.csv
  helpdesk_mgmt_sla/static/description/icon.png
  helpdesk_mgmt_sla/static/description/index.html
  helpdesk_mgmt_sla/tests/__init__.py
  helpdesk_mgmt_sla/tests/test_helpdesk_mgmt_sla.py
  helpdesk_mgmt_sla/views/helpdesk_sla_views.xml
  helpdesk_mgmt_sla/views/helpdesk_ticket_team_views.xml
  helpdesk_mgmt_sla/views/helpdesk_ticket_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#335 [FIX] helpdesk_motive: Website URL
  helpdesk_motive/__manifest__.py
Labels: bot is merging ⏳
