Repository OCA/helpdesk, pull requests merged in 2022-07, with the labels that each got.

#275 [14.0][IMP] helpdesk_mgmt: allow to define default team for a category
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_category.py
  helpdesk_mgmt/tests/test_helpdesk_ticket_team.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
Labels: approved, ready to merge, needs fixing, bot is merging ⏳

#346 [13.0][FIX] helpdesk_mgmtsystem_nonconformity: Avoid non-existing external_id error in action_nonconformity_create()
  helpdesk_mgmtsystem_nonconformity/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#326 [14.0][MIG] helpdesk_mgmt_sla
  helpdesk_mgmt_sla/README.rst
  helpdesk_mgmt_sla/__init__.py
  helpdesk_mgmt_sla/__manifest__.py
  helpdesk_mgmt_sla/data/helpdesk_sla_cron.xml
  helpdesk_mgmt_sla/demo/helpdesk_mgmt_sla_demo.xml
  helpdesk_mgmt_sla/i18n/es.po
  helpdesk_mgmt_sla/i18n/helpdesk_mgmt_sla.pot
  helpdesk_mgmt_sla/models/__init__.py
  helpdesk_mgmt_sla/models/helpdesk_sla.py
  helpdesk_mgmt_sla/models/helpdesk_ticket.py
  helpdesk_mgmt_sla/models/helpdesk_ticket_team.py
  helpdesk_mgmt_sla/readme/CONFIGURE.rst
  helpdesk_mgmt_sla/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_sla/readme/DESCRIPTION.rst
  helpdesk_mgmt_sla/readme/USAGE.rst
  helpdesk_mgmt_sla/security/ir.model.access.csv
  helpdesk_mgmt_sla/static/description/icon.png
  helpdesk_mgmt_sla/static/description/index.html
  helpdesk_mgmt_sla/tests/__init__.py
  helpdesk_mgmt_sla/tests/test_helpdesk_mgmt_sla.py
  helpdesk_mgmt_sla/views/helpdesk_sla_views.xml
  helpdesk_mgmt_sla/views/helpdesk_ticket_team_views.xml
  helpdesk_mgmt_sla/views/helpdesk_ticket_views.xml
  setup/helpdesk_mgmt_sla/odoo/addons/helpdesk_mgmt_sla
  setup/helpdesk_mgmt_sla/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#348 [14.0][MIG] helpdesk_mgmt_fieldservice: Migration to 14.0
  helpdesk_mgmt_fieldservice/README.rst
  helpdesk_mgmt_fieldservice/__init__.py
  helpdesk_mgmt_fieldservice/__manifest__.py
  helpdesk_mgmt_fieldservice/i18n/ca.po
  helpdesk_mgmt_fieldservice/i18n/es.po
  helpdesk_mgmt_fieldservice/i18n/fr.po
  helpdesk_mgmt_fieldservice/i18n/helpdesk_mgmt_fieldservice.pot
  helpdesk_mgmt_fieldservice/i18n/pt_BR.po
  helpdesk_mgmt_fieldservice/models/__init__.py
  helpdesk_mgmt_fieldservice/models/fsm_location.py
  helpdesk_mgmt_fieldservice/models/fsm_order.py
  helpdesk_mgmt_fieldservice/models/helpdesk_ticket.py
  helpdesk_mgmt_fieldservice/readme/CONFIGURE.rst
  helpdesk_mgmt_fieldservice/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_fieldservice/readme/DESCRIPTION.rst
  helpdesk_mgmt_fieldservice/readme/HISTORY.rst
  helpdesk_mgmt_fieldservice/readme/INSTALL.rst
  helpdesk_mgmt_fieldservice/readme/ROADMAP.rst
  helpdesk_mgmt_fieldservice/readme/USAGE.rst
  helpdesk_mgmt_fieldservice/security/ir.model.access.csv
  helpdesk_mgmt_fieldservice/static/description/icon.png
  helpdesk_mgmt_fieldservice/static/description/index.html
  helpdesk_mgmt_fieldservice/static/src/scss/helpdesk_column.scss
  helpdesk_mgmt_fieldservice/tests/__init__.py
  helpdesk_mgmt_fieldservice/tests/test_helpdesk_ticket_fsm_order.py
  helpdesk_mgmt_fieldservice/views/fsm_location_views.xml
  helpdesk_mgmt_fieldservice/views/fsm_order_views.xml
  helpdesk_mgmt_fieldservice/views/helpdesk_ticket_views.xml
  helpdesk_mgmt_fieldservice/views/res_partner.xml
  helpdesk_mgmt_fieldservice/wizards/__init__.py
  helpdesk_mgmt_fieldservice/wizards/fsm_order_close_wizard.py
  helpdesk_mgmt_fieldservice/wizards/fsm_order_close_wizard.xml
  setup/helpdesk_mgmt_fieldservice/odoo/addons/helpdesk_mgmt_fieldservice
  setup/helpdesk_mgmt_fieldservice/setup.py
Labels: approved, bot is merging ⏳
