Repository OCA/helpdesk, pull requests merged in 2023-10, with the labels that each got.

#508 [15.0][FIX] helpdesk_mgmt: Fixes to automatic email sending according to stage
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved

#510 [15.0][FIX] helpdesk_mgmt: Multi-company compatibility
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_tag_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_team_views.xml
Labels: approved, bot is merging ⏳

#509 [15.0][IMP] helpdesk_mgmt: Add empty option to Team and Category fields to portal ticket form
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/models/res_company.py
  helpdesk_mgmt/models/res_config_settings.py
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
  helpdesk_mgmt/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#511 [16.0][FIX] helpdesk_mgmt: Fixes to automatic email sending according to stage + Multi-company compatibility + Add empty option to Team and Category fields to portal ticket form
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/res_company.py
  helpdesk_mgmt/models/res_config_settings.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_tag_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_team_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
  helpdesk_mgmt/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#505 [16.0][FIX] helpdesk_mgmt_timesheet: Ticket submit broken
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/tests/test_helpdesk_portal.py
  helpdesk_mgmt_project/__init__.py
  helpdesk_mgmt_timesheet/__init__.py
  helpdesk_mgmt_timesheet/controllers/__init__.py
  helpdesk_mgmt_timesheet/controllers/main.py
  helpdesk_mgmt_timesheet/tests/__init__.py
  helpdesk_mgmt_timesheet/tests/test_helpdesk_portal.py
Labels: bot is merging ⏳

#470 [16.0][MIG] helpdesk_type
  helpdesk_type/README.rst
  helpdesk_type/__init__.py
  helpdesk_type/__manifest__.py
  helpdesk_type/demo/helpdesk_type_demo.xml
  helpdesk_type/i18n/es.po
  helpdesk_type/i18n/es_AR.po
  helpdesk_type/i18n/helpdesk_type.pot
  helpdesk_type/i18n/it.po
  helpdesk_type/i18n/pt.po
  helpdesk_type/i18n/pt_BR.po
  helpdesk_type/models/__init__.py
  helpdesk_type/models/helpdesk_ticket.py
  helpdesk_type/models/helpdesk_ticket_team.py
  helpdesk_type/models/helpdesk_ticket_type.py
  helpdesk_type/readme/CONFIGURE.rst
  helpdesk_type/readme/CONTRIBUTORS.rst
  helpdesk_type/readme/DESCRIPTION.rst
  helpdesk_type/readme/USAGE.rst
  helpdesk_type/security/ir.model.access.csv
  helpdesk_type/static/description/icon.png
  helpdesk_type/static/description/index.html
  helpdesk_type/tests/__init__.py
  helpdesk_type/tests/test_helpdesk_type.py
  helpdesk_type/views/helpdesk_ticket.xml
  helpdesk_type/views/helpdesk_ticket_team.xml
  helpdesk_type/views/helpdesk_ticket_type.xml
  setup/helpdesk_type/odoo/addons/helpdesk_type
  setup/helpdesk_type/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#513 [15.0][IMP] helpdesk_mgmt: tickets - add archived filter
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#515 [16.0][IMP] helpdesk_mgmt: tickets - add archived filter
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: bot is merging ⏳

#425 [15.0][MIG] helpdesk_mgmt_timesheet : Migration to 15.0
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/tests/test_helpdesk_portal.py
  helpdesk_mgmt_timesheet/README.rst
  helpdesk_mgmt_timesheet/__init__.py
  helpdesk_mgmt_timesheet/__manifest__.py
  helpdesk_mgmt_timesheet/demo/helpdesk_mgmt_timesheet_demo.xml
  helpdesk_mgmt_timesheet/i18n/es.po
  helpdesk_mgmt_timesheet/i18n/es_AR.po
  helpdesk_mgmt_timesheet/i18n/fr.po
  helpdesk_mgmt_timesheet/i18n/helpdesk_mgmt_timesheet.pot
  helpdesk_mgmt_timesheet/i18n/hu.po
  helpdesk_mgmt_timesheet/i18n/it.po
  helpdesk_mgmt_timesheet/models/__init__.py
  helpdesk_mgmt_timesheet/models/helpdesk_ticket.py
  helpdesk_mgmt_timesheet/models/helpdesk_ticket_team.py
  helpdesk_mgmt_timesheet/models/hr_timesheet.py
  helpdesk_mgmt_timesheet/readme/CONFIGURE.rst
  helpdesk_mgmt_timesheet/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_timesheet/readme/DESCRIPTION.rst
  helpdesk_mgmt_timesheet/readme/USAGE.rst
  helpdesk_mgmt_timesheet/report/report_timesheet_templates.xml
  helpdesk_mgmt_timesheet/static/description/icon.png
  helpdesk_mgmt_timesheet/static/description/index.html
  helpdesk_mgmt_timesheet/tests/__init__.py
  helpdesk_mgmt_timesheet/tests/test_helpdesk_mgmt_timesheet.py
  helpdesk_mgmt_timesheet/tests/test_helpdesk_portal.py
  helpdesk_mgmt_timesheet/tests/test_helpdesk_timesheet_time_control.py
  helpdesk_mgmt_timesheet/views/helpdesk_project_task_view.xml
  helpdesk_mgmt_timesheet/views/helpdesk_team_view.xml
  helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
  helpdesk_mgmt_timesheet/views/hr_timesheet_view.xml
  helpdesk_mgmt_timesheet/wizards/__init__.py
  helpdesk_mgmt_timesheet/wizards/hr_timesheet_switch.py
  setup/helpdesk_mgmt_timesheet/odoo/addons/helpdesk_mgmt_timesheet
  setup/helpdesk_mgmt_timesheet/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#518 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_tag_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_team_views.xml
  helpdesk_mgmt_fieldservice/views/helpdesk_ticket_views.xml
  helpdesk_mgmt_sla/demo/helpdesk_mgmt_sla_demo.xml
  helpdesk_mgmt_sla/i18n/helpdesk_mgmt_sla.pot
  helpdesk_mgmt_sla/views/helpdesk_sla_views.xml
  helpdesk_mgmt_timesheet/demo/helpdesk_mgmt_timesheet_demo.xml
  helpdesk_motive/demo/helpdesk_motive_demo.xml
  helpdesk_motive/i18n/helpdesk_motive.pot
  helpdesk_motive/views/helpdesk_ticket_motive.xml
  helpdesk_type/demo/helpdesk_type_demo.xml
  helpdesk_type/i18n/helpdesk_type.pot
  helpdesk_type/views/helpdesk_ticket_type.xml
Labels: help wanted, needs review, bot is merging ⏳
