Repository OCA/helpdesk, pull requests merged in 2023-01, with the labels that each got.

#406 [14.0][IMP] helpdesk_mgmt: creation of ticket notified to followers of the team assigned
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved

#395 [13.0][IMP] helpdesk_mgmt: User: Team tickets group
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/migrations/13.0.1.14.0/post-migration.py
  helpdesk_mgmt/models/__init__.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_team.py
  helpdesk_mgmt/models/res_partner.py
  helpdesk_mgmt/models/res_users.py
  helpdesk_mgmt/readme/CONFIGURE.rst
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/static/description/index.html
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#410 [13.0][IMP] helpdesk_mgmt: creation of ticket notified to followers of the team assigned
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#408 [14.0][IMP] helpdesk_mgmt: User: Team tickets group
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/migrations/14.0.1.17.0/post-migration.py
  helpdesk_mgmt/models/__init__.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_team.py
  helpdesk_mgmt/models/res_partner.py
  helpdesk_mgmt/models/res_users.py
  helpdesk_mgmt/readme/CONFIGURE.rst
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/static/description/index.html
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#412 [15.0][IMP] helpdesk_mgmt: User: Team tickets group
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/migrations/15.0.2.4.0/post-migration.py
  helpdesk_mgmt/models/__init__.py
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_team.py
  helpdesk_mgmt/models/res_partner.py
  helpdesk_mgmt/models/res_users.py
  helpdesk_mgmt/readme/CONFIGURE.rst
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/static/description/index.html
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#413 [15.0][IMP] helpdesk_mgmt: creation of ticket notified to followers of the team assigned
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#409 [14.0][FIX] helpdesk_mgmt: assigned date empty and creation method to multi
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#417 [14.0][FIX] helpdesk_motive: onchange removed in base module.
  helpdesk_motive/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#415 [14.0][IMP] helpdesk_mgmt_project: apply default project to tickets from portal.
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt_project/__init__.py
  helpdesk_mgmt_project/controllers/__init__.py
  helpdesk_mgmt_project/controllers/main.py
Labels: bot is merging ⏳

#414 [15.0][FIX] helpdesk_mgmt: assigned date empty and creation method to multi
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, ready to merge, bot is merging ⏳

#416 [13.0][IMP] helpdesk_mgmt: Only show tickets of the user's helpdesk team with "User: Team tickets" permission.
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/migrations/13.0.2.2.0/noupdate_changes.xml
  helpdesk_mgmt/migrations/13.0.2.2.0/post-migration.py
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/tests/common.py
  helpdesk_mgmt/tests/test_helpdesk_ticket.py
  helpdesk_mgmt/tests/test_helpdesk_ticket_team.py
  helpdesk_mgmt/tests/test_res_partner.py
  helpdesk_mgmt_project/tests/test_helpdesk_ticket.py
Labels: bot is merging ⏳

#418 [14.0][IMP] helpdesk_mgmt: Only show tickets of the user's helpdesk team with "User: Team tickets" permission.
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/migrations/14.0.2.1.0/noupdate_changes.xml
  helpdesk_mgmt/migrations/14.0.2.1.0/post-migration.py
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/tests/common.py
  helpdesk_mgmt/tests/test_helpdesk_ticket.py
  helpdesk_mgmt/tests/test_helpdesk_ticket_team.py
  helpdesk_mgmt/tests/test_res_partner.py
  helpdesk_mgmt_project/tests/test_helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#419 [15.0][IMP] helpdesk_mgmt: Only show tickets of the user's helpdesk team with "User: Team tickets" permission
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/migrations/15.0.3.2.0/noupdate_changes.xml
  helpdesk_mgmt/migrations/15.0.3.2.0/post-migration.py
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/tests/common.py
  helpdesk_mgmt/tests/test_helpdesk_ticket.py
  helpdesk_mgmt/tests/test_helpdesk_ticket_team.py
  helpdesk_mgmt/tests/test_res_partner.py
  helpdesk_mgmt_project/tests/test_helpdesk_ticket.py
  helpdesk_type/tests/test_helpdesk_type.py
Labels: approved, bot is merging ⏳

#383 [15.0][IMP] helpdesk_mgmt: Add "close from portal" option & test
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/models/helpdesk_ticket_stage.py
  helpdesk_mgmt/readme/ROADMAP.rst
  helpdesk_mgmt/tests/test_portal.py
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#421 [13.0][IMP] helpdesk_mgmt: Add sequence field to category, channel and team objects.
  helpdesk_mgmt/models/helpdesk_ticket_category.py
  helpdesk_mgmt/models/helpdesk_ticket_channel.py
  helpdesk_mgmt/models/helpdesk_ticket_team.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_team_views.xml
Labels: approved, bot is merging ⏳

#386 [15.0][MIG] helpdesk_mgmt_rating: Migration to 15.0
  helpdesk_mgmt_rating/README.rst
  helpdesk_mgmt_rating/__init__.py
  helpdesk_mgmt_rating/__manifest__.py
  helpdesk_mgmt_rating/data/helpdesk_data.xml
  helpdesk_mgmt_rating/i18n/es.po
  helpdesk_mgmt_rating/i18n/es_AR.po
  helpdesk_mgmt_rating/i18n/fr.po
  helpdesk_mgmt_rating/i18n/helpdesk_mgmt_rating.pot
  helpdesk_mgmt_rating/i18n/it.po
  helpdesk_mgmt_rating/migrations/15.0.1.0.0/noupdate_changes.xml
  helpdesk_mgmt_rating/migrations/15.0.1.0.0/post-migration.py
  helpdesk_mgmt_rating/models/__init__.py
  helpdesk_mgmt_rating/models/helpdesk_ticket.py
  helpdesk_mgmt_rating/models/helpdesk_ticket_stage.py
  helpdesk_mgmt_rating/readme/CONFIGURE.rst
  helpdesk_mgmt_rating/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_rating/readme/DESCRIPTION.rst
  helpdesk_mgmt_rating/static/description/icon.png
  helpdesk_mgmt_rating/static/description/index.html
  helpdesk_mgmt_rating/tests/__init__.py
  helpdesk_mgmt_rating/tests/test_helpdesk_mgmt_rating.py
  helpdesk_mgmt_rating/views/helpdesk_ticket_menu.xml
  helpdesk_mgmt_rating/views/helpdesk_ticket_stage_views.xml
  helpdesk_mgmt_rating/views/helpdesk_ticket_views.xml
  setup/helpdesk_mgmt_rating/odoo/addons/helpdesk_mgmt_rating
  setup/helpdesk_mgmt_rating/setup.py
Labels: approved, bot is merging ⏳

#422 [14.0][IMP] helpdesk_mgmt: Add sequence field to category, channel and team objects
  helpdesk_mgmt/models/helpdesk_ticket_category.py
  helpdesk_mgmt/models/helpdesk_ticket_channel.py
  helpdesk_mgmt/models/helpdesk_ticket_team.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_team_views.xml
Labels: approved, bot is merging ⏳

#424 [15.0][IMP] helpdesk_mgmt: Add sequence field to category, channel and team objects
  helpdesk_mgmt/models/helpdesk_ticket_category.py
  helpdesk_mgmt/models/helpdesk_ticket_channel.py
  helpdesk_mgmt/models/helpdesk_ticket_team.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_team_views.xml
Labels: approved, bot is merging ⏳

#426 [13.0][IMP] helpdesk_mgmt: Add base user to show tickets
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/security/ir.model.access.csv
  helpdesk_mgmt/tests/__init__.py
  helpdesk_mgmt/tests/test_helpdesk_portal.py
Labels: approved, bot is merging ⏳

#427 [14.0][IMP] helpdesk_mgmt: Add base user to show tickets
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/security/ir.model.access.csv
  helpdesk_mgmt/tests/__init__.py
  helpdesk_mgmt/tests/test_helpdesk_portal.py
Labels: approved, bot is merging ⏳

#429 [13.0][IMP] helpdesk_mgmt: Fix Internal Tickets rule to prevent see other users' tickets + improve tests
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/migrations/13.0.2.5.0/noupdate_changes.xml
  helpdesk_mgmt/migrations/13.0.2.5.0/post-migration.py
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/tests/test_helpdesk_portal.py
Labels: bot is merging ⏳

#430 [14.0][IMP] helpdesk_mgmt: Fix Internal Tickets rule to prevent see other users' tickets + improve tests
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/migrations/14.0.2.4.0/noupdate_changes.xml
  helpdesk_mgmt/migrations/14.0.2.4.0/post-migration.py
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/tests/test_helpdesk_portal.py
Labels: approved, bot is merging ⏳

#428 [15.0][IMP] helpdesk_mgmt: Add base user to show tickets
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/security/ir.model.access.csv
  helpdesk_mgmt/tests/__init__.py
  helpdesk_mgmt/tests/test_helpdesk_portal.py
Labels: approved, bot is merging ⏳
