Repository OCA/helpdesk, pull requests merged in 2023-07, with the labels that each got.

#482 [15.0][IMP] helpdesk_mgmt: Delete unused record
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/migrations/15.0.3.6.1/post-migration.py
Labels: approved, bot is merging ⏳

#478 [15.0][IMP] helpdesk_mgmt: tags - visual and functional adjustments
  helpdesk_mgmt/views/helpdesk_ticket_tag_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#480 [16.0][FIX] helpdesk_mgmt_project: improve performance counting tickets
  helpdesk_mgmt_project/README.rst
  helpdesk_mgmt_project/models/project.py
  helpdesk_mgmt_project/models/project_task.py
  helpdesk_mgmt_project/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_project/static/description/index.html
Labels: approved, bot is merging ⏳

#479 [15.0][FIX] helpdesk_mgmt_project: improve performance counting tickets
  helpdesk_mgmt_project/README.rst
  helpdesk_mgmt_project/models/project.py
  helpdesk_mgmt_project/models/project_task.py
  helpdesk_mgmt_project/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_project/static/description/index.html
Labels: approved, bot is merging ⏳

#485 [16.0][IMP] helpdesk_mgmt: tags - visual and functional adjustments
  helpdesk_mgmt/views/helpdesk_ticket_tag_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#486 [15.0][IMP] helpdesk_mgmt: Change toggle_active to web_ribbon
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
Labels: approved, bot is merging ⏳

#477 [14.0][ADD] helpdesk_mgmt_timesheet: add optional ticket field in view
  helpdesk_mgmt_timesheet/__manifest__.py
  helpdesk_mgmt_timesheet/views/helpdesk_project_task_view.xml
Labels: approved, bot is merging ⏳

#489 [15.0][OU-FIX] helpdesk_mgmt: Add noupdate_changes to update the values of the email templates
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/migrations/15.0.1.0.0/noupdate_changes.xml
  helpdesk_mgmt/migrations/15.0.1.0.0/post-migration.py
Labels: approved, bot is merging ⏳

#492 [14.0][FIX] helpdesk_mgmt: hide false name when send email when change stage
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/data/helpdesk_data.xml
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/migrations/14.0.2.11.0/noupdate_changes.xml
  helpdesk_mgmt/migrations/14.0.2.11.0/post-migration.py
Labels: approved, bot is merging ⏳

#494 [16.0][FW-PORT] helpdesk_mgmt: Sequence field added to sort tickets
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: bot is merging ⏳

#497 [16.0][FIX] helpdesk_mgmt: Reintroduce `create_date` in list view
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: bot is merging ⏳

#496 [15.0][FW-PORT] helpdesk_mgmt: Sequence field added to sort tickets
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: bot is merging ⏳
