Repository OCA/helpdesk, pull requests merged in 2024-11, with the labels that each got.

#551 [FIX[[16] helpdesk_mgmt_project: Fix id instead of active_id used in smartbuttons
  helpdesk_mgmt_project/views/project_view.xml
Labels: approved, bot is merging ⏳, stale

#656 [15.0][FIX] helpdesk_mgmt_timesheet: Remove field access restriction
  helpdesk_mgmt_timesheet/models/hr_timesheet.py
Labels: approved, bot is merging ⏳

#643 [16.0][IMP]helpdesk_mgmt: email channel
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/tests/__init__.py
  helpdesk_mgmt/tests/test_helpdesk_fetchmail.py
Labels: approved, ready to merge, bot is merging ⏳

#658 [17.0][IMP]helpdesk_mgmt: email channel
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/tests/__init__.py
  helpdesk_mgmt/tests/test_helpdesk_fetchmail.py
Labels: bot is merging ⏳

#651 [16.0][ADD] helpdesk_ticket_close_inactive
  helpdesk_ticket_close_inactive/README.rst
  helpdesk_ticket_close_inactive/__init__.py
  helpdesk_ticket_close_inactive/__manifest__.py
  helpdesk_ticket_close_inactive/data/helpdesk_data.xml
  helpdesk_ticket_close_inactive/i18n/es.po
  helpdesk_ticket_close_inactive/models/__init__.py
  helpdesk_ticket_close_inactive/models/helpdesk_ticket_team.py
  helpdesk_ticket_close_inactive/readme/CONFIGURE.md
  helpdesk_ticket_close_inactive/readme/CONTRIBUTORS.md
  helpdesk_ticket_close_inactive/readme/DESCRIPTION.md
  helpdesk_ticket_close_inactive/readme/newsfragments/.gitkeep
  helpdesk_ticket_close_inactive/static/description/icon.png
  helpdesk_ticket_close_inactive/static/description/icon.svg
  helpdesk_ticket_close_inactive/static/description/index.html
  helpdesk_ticket_close_inactive/tests/__init__.py
  helpdesk_ticket_close_inactive/tests/test_ticket_autoclose.py
  helpdesk_ticket_close_inactive/views/helpdesk_ticket_team.xml
  setup/helpdesk_ticket_close_inactive/odoo/addons/helpdesk_ticket_close_inactive
  setup/helpdesk_ticket_close_inactive/setup.py
Labels: approved, ready to merge, bot is merging ⏳
