Repository OCA/helpdesk, pull requests merged in 2024-04, with the labels that each got.

#555 [16.0][IMP] helpdesk_mgmt_project: Improve project kanban view
  helpdesk_mgmt_project/views/project_view.xml
Labels: approved, bot is merging ⏳

#521 [15.0][FIX+IMP] helpdesk_type: some views adjustments
  helpdesk_type/views/helpdesk_ticket.xml
  helpdesk_type/views/helpdesk_ticket_team.xml
Labels: bug, enhancement, needs review, bot is merging ⏳

#558 [16.0][FIX+IMP] helpdesk_type: some views adjustments
  helpdesk_type/views/helpdesk_ticket.xml
  helpdesk_type/views/helpdesk_ticket_team.xml
Labels: approved, bot is merging ⏳

#520 [16.0][ADD] helpdesk_product
  helpdesk_product/README.rst
  helpdesk_product/__init__.py
  helpdesk_product/__manifest__.py
  helpdesk_product/demo/helpdesk_product_demo.xml
  helpdesk_product/models/__init__.py
  helpdesk_product/models/helpdesk_ticket.py
  helpdesk_product/models/product.py
  helpdesk_product/readme/CONTRIBUTORS.rst
  helpdesk_product/readme/DESCRIPTION.rst
  helpdesk_product/views/helpdesk_ticket_view.xml
  helpdesk_product/views/product_view.xml
  setup/helpdesk_product/odoo/addons/helpdesk_product
  setup/helpdesk_product/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#557 [16.0] [FIX] helpdesk_mgmt: use company of team on tickets when team is defined
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, ready to merge, bot is merging ⏳

#561 [15.0][IMP] helpdesk_mgmt: Show error if file size exceeds limit
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/static/description/index.html
  helpdesk_mgmt/static/src/js/new_ticket.js
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳

#554 [16.0][MIG] helpdesk_mgmt_rating: Migration to 16.0
  helpdesk_mgmt_rating/README.rst
  helpdesk_mgmt_rating/__init__.py
  helpdesk_mgmt_rating/__manifest__.py
  helpdesk_mgmt_rating/data/helpdesk_data.xml
  helpdesk_mgmt_rating/i18n/es.po
  helpdesk_mgmt_rating/i18n/es_AR.po
  helpdesk_mgmt_rating/i18n/fr.po
  helpdesk_mgmt_rating/i18n/helpdesk_mgmt_rating.pot
  helpdesk_mgmt_rating/i18n/it.po
  helpdesk_mgmt_rating/migrations/16.0.1.0.0/noupdate_changes.xml
  helpdesk_mgmt_rating/migrations/16.0.1.0.0/post-migration.py
  helpdesk_mgmt_rating/models/__init__.py
  helpdesk_mgmt_rating/models/helpdesk_ticket.py
  helpdesk_mgmt_rating/models/helpdesk_ticket_stage.py
  helpdesk_mgmt_rating/readme/CONFIGURE.rst
  helpdesk_mgmt_rating/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_rating/readme/DESCRIPTION.rst
  helpdesk_mgmt_rating/static/description/icon.png
  helpdesk_mgmt_rating/static/description/index.html
  helpdesk_mgmt_rating/tests/__init__.py
  helpdesk_mgmt_rating/tests/test_helpdesk_mgmt_rating.py
  helpdesk_mgmt_rating/tests/test_helpdesk_portal.py
  helpdesk_mgmt_rating/views/helpdesk_ticket_menu.xml
  helpdesk_mgmt_rating/views/helpdesk_ticket_stage_views.xml
  helpdesk_mgmt_rating/views/helpdesk_ticket_views.xml
  setup/helpdesk_mgmt_rating/odoo/addons/helpdesk_mgmt_rating
  setup/helpdesk_mgmt_rating/setup.py
Labels: approved, bot is merging ⏳

#562 [15.0][FIX] helpdesk_mgmt: Make frontend js files translatables
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/models/__init__.py
  helpdesk_mgmt/models/ir_http.py
  helpdesk_mgmt/readme/CONTRIBUTORS.rst
  helpdesk_mgmt/static/description/index.html
Labels: approved, bot is merging ⏳

#563 [16.0][IMP] helpdesk_mgmt: Show error if file size exceeds limit
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/models/__init__.py
  helpdesk_mgmt/models/ir_http.py
  helpdesk_mgmt/readme/CONTRIBUTORS.rst
  helpdesk_mgmt/static/description/index.html
  helpdesk_mgmt/static/src/js/new_ticket.js
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳

#565 [14.0][BACKPORT]helpdesk_mgmt: add archived ribbon to ticket stage form view
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_channel_views.xml
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
Labels: approved, bot is merging ⏳
