Repository OCA/helpdesk, pull requests merged in 2024-06, with the labels that each got.

#585 [16.0][FIX]helpdesk_mgmt: portal ACL on team
  helpdesk_mgmt/security/helpdesk_security.xml
  helpdesk_mgmt/security/ir.model.access.csv
Labels: approved, ready to merge, bot is merging ⏳

#583 [16.0][IMP]helpdesk_mgmt: Add commercial partner on ticket
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#582 [16.0][IMP] helpdesk_mgmt_timesheet: add optional ticket field in view and add avatar widget
  helpdesk_mgmt_timesheet/__manifest__.py
  helpdesk_mgmt_timesheet/views/helpdesk_project_task_view.xml
  helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#587 [14.0][FIX] helpdesk_mgmt: fix customer image on portal
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳

#590 [FIX][16.0]helpdesk_mgmt_timesheet: add proper import to trigger the proper closest suggestion
  helpdesk_mgmt_timesheet/__init__.py
  helpdesk_mgmt_timesheet/wizards/hr_timesheet_switch.py
Labels: approved, bot is merging ⏳

#588 [16.0][FIX] helpdesk_mgmt: Tag tests as per recommendations for HttpCase type tests.
  helpdesk_mgmt/__manifest__.py
  helpdesk_mgmt/tests/test_helpdesk_portal.py
Labels: bot is merging ⏳
