Repository OCA/helpdesk, pull requests merged in 2024-09, with the labels that each got.

#553 [15.0] [FIX] helpdesk_mgmt: company_id should come from team
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#619 Revert "[15.0] [FIX] helpdesk_mgmt: company_id should come from team"
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: needs review, bot is merging ⏳

#622 [15.0][FIX] helpdesk_mgmt: use company of team on tickets when team is defined
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#621 [16.0][IMP] helpdesk_mgmt: Add specific use cases with team without company_id
  helpdesk_mgmt/tests/common.py
  helpdesk_mgmt/tests/test_helpdesk_ticket.py
Labels: approved, ready to merge, bot is merging ⏳

#620 [15.0][IMP] helpdesk_mgmt: Add specific use cases with team without company_id
  helpdesk_mgmt/tests/common.py
  helpdesk_mgmt/tests/test_helpdesk_ticket.py
Labels: approved, ready to merge, bot is merging ⏳

#626 [16.0] [IMP] helpdesk_mgmt_project: Add groups to project/helpdesk fields
  helpdesk_mgmt_project/views/helpdesk_ticket_team_view.xml
  helpdesk_mgmt_project/views/helpdesk_ticket_view.xml
  helpdesk_mgmt_project/views/project_task_view.xml
  helpdesk_mgmt_project/views/project_view.xml
Labels: approved, bot is merging ⏳

#627 [15.0][MIG] helpdesk_mgmt_crm: Migration to 15.0
  helpdesk_mgmt_crm/README.rst
  helpdesk_mgmt_crm/__init__.py
  helpdesk_mgmt_crm/__manifest__.py
  helpdesk_mgmt_crm/i18n/es.po
  helpdesk_mgmt_crm/i18n/helpdesk_mgmt_crm.pot
  helpdesk_mgmt_crm/models/__init__.py
  helpdesk_mgmt_crm/models/crm_lead.py
  helpdesk_mgmt_crm/models/helpdesk_ticket.py
  helpdesk_mgmt_crm/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_crm/readme/DESCRIPTION.rst
  helpdesk_mgmt_crm/readme/USAGE.rst
  helpdesk_mgmt_crm/security/ir.model.access.csv
  helpdesk_mgmt_crm/static/description/icon.png
  helpdesk_mgmt_crm/static/description/index.html
  helpdesk_mgmt_crm/tests/__init__.py
  helpdesk_mgmt_crm/tests/test_helpdesk_mgmt_crm.py
  helpdesk_mgmt_crm/views/crm_lead_view.xml
  helpdesk_mgmt_crm/views/helpdesk_ticket_view.xml
  helpdesk_mgmt_crm/wizard/__init__.py
  helpdesk_mgmt_crm/wizard/helpdesk_ticket_create_lead.py
  helpdesk_mgmt_crm/wizard/helpdesk_ticket_create_lead_views.xml
  setup/helpdesk_mgmt_crm/odoo/addons/helpdesk_mgmt_crm
  setup/helpdesk_mgmt_crm/setup.py
Labels: approved, bot is merging ⏳

#628 [15.0][ADD] helpdesk_mgmt_sale: Add new module
  helpdesk_mgmt_sale/README.rst
  helpdesk_mgmt_sale/__init__.py
  helpdesk_mgmt_sale/__manifest__.py
  helpdesk_mgmt_sale/models/__init__.py
  helpdesk_mgmt_sale/models/helpdesk_ticket.py
  helpdesk_mgmt_sale/models/sale_order.py
  helpdesk_mgmt_sale/readme/CONTRIBUTORS.rst
  helpdesk_mgmt_sale/readme/DESCRIPTION.rst
  helpdesk_mgmt_sale/readme/USAGE.rst
  helpdesk_mgmt_sale/static/description/icon.png
  helpdesk_mgmt_sale/static/description/icon.svg
  helpdesk_mgmt_sale/static/description/index.html
  helpdesk_mgmt_sale/tests/__init__.py
  helpdesk_mgmt_sale/tests/test_helpdesk_ticket.py
  helpdesk_mgmt_sale/views/helpdesk_ticket_views.xml
  helpdesk_mgmt_sale/views/sale_order_views.xml
  setup/helpdesk_mgmt_sale/odoo/addons/helpdesk_mgmt_sale
  setup/helpdesk_mgmt_sale/setup.py
Labels: approved, bot is merging ⏳

#625 [14.0][FIX] helpdesk_mgmt_timesheet allow_timesheet accessible from all user
  helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#630 [16.0][FIX] helpdesk_mgmt_timesheet: allow_timesheet accessible from all user
  helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
Labels: approved, bot is merging ⏳

#629 [15.0][FIX] helpdesk_mgmt_timesheet: allow_timesheet accessible from all user
  helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
Labels: approved, bot is merging ⏳

#632 [15.0][IMP] helpdesk_mgmt_sale: Allow to assign multiple tickets to an order
  helpdesk_mgmt_sale/__manifest__.py
  helpdesk_mgmt_sale/migrations/15.0.2.0.0/post-migration.py
  helpdesk_mgmt_sale/models/helpdesk_ticket.py
  helpdesk_mgmt_sale/models/sale_order.py
  helpdesk_mgmt_sale/tests/test_helpdesk_ticket.py
  helpdesk_mgmt_sale/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#631 [16.0][FIX] helpdesk_mgmt_timesheet: Apply the required attrs to the project_id field which has groups
  helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
Labels: bot is merging ⏳
