Repository OCA/helpdesk, pull requests merged in 2025-08, with the labels that each got.

#752 [18.0][IMP] helpdesk_mgmt: Add team hierarchy
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/models/helpdesk_ticket_team.py
  helpdesk_mgmt/readme/CONTRIBUTORS.md
  helpdesk_mgmt/static/description/index.html
  helpdesk_mgmt/tests/test_helpdesk_ticket_team.py
  helpdesk_mgmt/views/helpdesk_ticket_team_views.xml
Labels: bot is merging ⏳

#805 [18.0][FIX] helpdesk_mgmt: Fix hierarchical categories in portal view
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#818 [18.0][ADD] helpdesk_mgmt_fieldservice_equipment
  helpdesk_mgmt_fieldservice_equipment/README.rst
  helpdesk_mgmt_fieldservice_equipment/__init__.py
  helpdesk_mgmt_fieldservice_equipment/__manifest__.py
  helpdesk_mgmt_fieldservice_equipment/models/__init__.py
  helpdesk_mgmt_fieldservice_equipment/models/fsm_equipment.py
  helpdesk_mgmt_fieldservice_equipment/models/helpdesk_ticket.py
  helpdesk_mgmt_fieldservice_equipment/pyproject.toml
  helpdesk_mgmt_fieldservice_equipment/readme/CONTRIBUTORS.md
  helpdesk_mgmt_fieldservice_equipment/readme/DESCRIPTION.md
  helpdesk_mgmt_fieldservice_equipment/static/description/index.html
  helpdesk_mgmt_fieldservice_equipment/tests/__init__.py
  helpdesk_mgmt_fieldservice_equipment/tests/test_fsm_equipment.py
  helpdesk_mgmt_fieldservice_equipment/tests/test_helpdesk_ticket.py
  helpdesk_mgmt_fieldservice_equipment/views/helpdesk_ticket.xml
Labels: approved, bot is merging ⏳

#807 [17.0] [IMP] helpdesk_mgmt: categories visibility in portal
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/models/helpdesk_ticket_category.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#822 [16.0][IMP] helpdesk_mgmt: Improve usage of Kanban State
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#800 [18.0][MIG] helpdesk_mgmt_sla
  helpdesk_mgmt_sla/README.rst
  helpdesk_mgmt_sla/__init__.py
  helpdesk_mgmt_sla/__manifest__.py
  helpdesk_mgmt_sla/data/helpdesk_sla_cron.xml
  helpdesk_mgmt_sla/demo/helpdesk_mgmt_sla_demo.xml
  helpdesk_mgmt_sla/i18n/es.po
  helpdesk_mgmt_sla/i18n/es_AR.po
  helpdesk_mgmt_sla/i18n/helpdesk_mgmt_sla.pot
  helpdesk_mgmt_sla/i18n/it.po
  helpdesk_mgmt_sla/i18n/pt.po
  helpdesk_mgmt_sla/i18n/tr.po
  helpdesk_mgmt_sla/models/__init__.py
  helpdesk_mgmt_sla/models/helpdesk_sla.py
  helpdesk_mgmt_sla/models/helpdesk_ticket.py
  helpdesk_mgmt_sla/models/helpdesk_ticket_team.py
  helpdesk_mgmt_sla/pyproject.toml
  helpdesk_mgmt_sla/readme/CONFIGURE.md
  helpdesk_mgmt_sla/readme/CONTRIBUTORS.md
  helpdesk_mgmt_sla/readme/DESCRIPTION.md
  helpdesk_mgmt_sla/readme/USAGE.md
  helpdesk_mgmt_sla/security/ir.model.access.csv
  helpdesk_mgmt_sla/static/description/icon.png
  helpdesk_mgmt_sla/static/description/index.html
  helpdesk_mgmt_sla/tests/__init__.py
  helpdesk_mgmt_sla/tests/common.py
  helpdesk_mgmt_sla/tests/test_helpdesk_mgmt_sla.py
  helpdesk_mgmt_sla/views/helpdesk_sla_views.xml
  helpdesk_mgmt_sla/views/helpdesk_ticket_team_views.xml
  helpdesk_mgmt_sla/views/helpdesk_ticket_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#823 [16.0][FIX] helpdesk mgmt fix ticket create message
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/tests/test_helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#801 [18.0][MIG] helpdesk_type_sla
  helpdesk_type_sla/README.rst
  helpdesk_type_sla/__init__.py
  helpdesk_type_sla/__manifest__.py
  helpdesk_type_sla/i18n/es.po
  helpdesk_type_sla/i18n/es_AR.po
  helpdesk_type_sla/i18n/helpdesk_type_sla.pot
  helpdesk_type_sla/i18n/it.po
  helpdesk_type_sla/i18n/pt.po
  helpdesk_type_sla/models/__init__.py
  helpdesk_type_sla/models/helpdesk_sla.py
  helpdesk_type_sla/pyproject.toml
  helpdesk_type_sla/readme/CONTRIBUTORS.md
  helpdesk_type_sla/readme/DESCRIPTION.md
  helpdesk_type_sla/static/description/icon.png
  helpdesk_type_sla/static/description/index.html
  helpdesk_type_sla/tests/__init__.py
  helpdesk_type_sla/tests/test_helpdesk_mgmt_sla_type.py
  helpdesk_type_sla/views/helpdesk_sla_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#825 [16.0][FIX] helpdesk_mgmt_stage_validation: prevent access error when checking required fields using fields_get with sudo
  helpdesk_mgmt_stage_validation/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳
