Repository OCA/helpdesk, pull requests merged in 2025-05, with the labels that each got.

#660 [16.0][IMP]helpdesk_mgmt: show stage colours in portal as in normal view
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#723 [17.0][IMP] helpdesk_mgmt: ticket categories hierarchy support
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/demo/helpdesk_demo.xml
  helpdesk_mgmt/models/helpdesk_ticket_category.py
  helpdesk_mgmt/readme/CONTRIBUTORS.md
  helpdesk_mgmt/static/description/index.html
  helpdesk_mgmt/tests/__init__.py
  helpdesk_mgmt/tests/test_helpdesk_category_hierarchy.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
Labels: approved, bot is merging ⏳

#739 [17.0][IMP] helpdesk_mgmt_timesheet: fix keyerror 'active_model'
  helpdesk_mgmt_timesheet/wizards/hr_timesheet_switch.py
Labels: approved, bot is merging ⏳

#668 [16.0] [FIX] helpdesk_mgmt preventing to select partner of wrong company when user has more than 1 company active
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#673 [16.0][ADD] helpdesk_mgmt_project_stage
  helpdesk_mgmt_project_stage/README.rst
  helpdesk_mgmt_project_stage/__init__.py
  helpdesk_mgmt_project_stage/__manifest__.py
  helpdesk_mgmt_project_stage/demo/project_task_type.xml
  helpdesk_mgmt_project_stage/models/__init__.py
  helpdesk_mgmt_project_stage/models/helpdesk_ticket.py
  helpdesk_mgmt_project_stage/models/helpdesk_ticket_stage.py
  helpdesk_mgmt_project_stage/models/project_task.py
  helpdesk_mgmt_project_stage/models/project_task_type.py
  helpdesk_mgmt_project_stage/readme/CONFIGURE.md
  helpdesk_mgmt_project_stage/readme/CONTRIBUTORS.md
  helpdesk_mgmt_project_stage/readme/DESCRIPTION.md
  helpdesk_mgmt_project_stage/readme/USAGE.md
  helpdesk_mgmt_project_stage/static/description/icon.png
  helpdesk_mgmt_project_stage/tests/__init__.py
  helpdesk_mgmt_project_stage/tests/test_helpdesk_mgmt_project_stage.py
  helpdesk_mgmt_project_stage/views/helpdesk_ticket_state.xml
  helpdesk_mgmt_project_stage/views/project_task_type.xml
  setup/helpdesk_mgmt_project_stage/odoo/addons/helpdesk_mgmt_project_stage
  setup/helpdesk_mgmt_project_stage/setup.py
Labels: approved, bot is merging ⏳, stale

#742 [18.0][IMP] helpdesk_mgmt: ticket categories hierarchy support
  helpdesk_mgmt/README.rst
  helpdesk_mgmt/demo/helpdesk_demo.xml
  helpdesk_mgmt/models/helpdesk_ticket_category.py
  helpdesk_mgmt/readme/CONTRIBUTORS.md
  helpdesk_mgmt/static/description/index.html
  helpdesk_mgmt/tests/__init__.py
  helpdesk_mgmt/tests/test_helpdesk_category_hierarchy.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
Labels: approved, bot is merging ⏳

#645 [16.0][IMP]helpdesk_mgmt: allow to define default team for a category
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/models/helpdesk_ticket_category.py
  helpdesk_mgmt/tests/test_helpdesk_ticket_team.py
  helpdesk_mgmt/views/helpdesk_ticket_category_views.xml
Labels: approved, bot is merging ⏳

#699 [18.0][MIG] helpdesk_mgmt_merge: Migration to 18.0
  helpdesk_mgmt_merge/README.rst
  helpdesk_mgmt_merge/__init__.py
  helpdesk_mgmt_merge/__manifest__.py
  helpdesk_mgmt_merge/i18n/helpdesk_mgmt_merge.pot
  helpdesk_mgmt_merge/i18n/it.po
  helpdesk_mgmt_merge/pyproject.toml
  helpdesk_mgmt_merge/readme/CONTRIBUTORS.md
  helpdesk_mgmt_merge/readme/DESCRIPTION.md
  helpdesk_mgmt_merge/readme/USAGE.md
  helpdesk_mgmt_merge/security/ir.model.access.csv
  helpdesk_mgmt_merge/static/description/icon.png
  helpdesk_mgmt_merge/static/description/index.html
  helpdesk_mgmt_merge/tests/__init__.py
  helpdesk_mgmt_merge/tests/test_helpdesk_mgmt_merge.py
  helpdesk_mgmt_merge/wizard/__init__.py
  helpdesk_mgmt_merge/wizard/helpdesk_ticket_merge.py
  helpdesk_mgmt_merge/wizard/helpdesk_ticket_merge_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#702 [18.0][MIG] helpdesk_motive: Migration to 18.0
  helpdesk_motive/README.rst
  helpdesk_motive/__init__.py
  helpdesk_motive/__manifest__.py
  helpdesk_motive/demo/helpdesk_motive_demo.xml
  helpdesk_motive/i18n/es.po
  helpdesk_motive/i18n/es_AR.po
  helpdesk_motive/i18n/fr.po
  helpdesk_motive/i18n/helpdesk_motive.pot
  helpdesk_motive/i18n/it.po
  helpdesk_motive/i18n/pt.po
  helpdesk_motive/i18n/pt_BR.po
  helpdesk_motive/i18n/sv.po
  helpdesk_motive/models/__init__.py
  helpdesk_motive/models/helpdesk_ticket.py
  helpdesk_motive/models/helpdesk_ticket_motive.py
  helpdesk_motive/models/helpdesk_ticket_team.py
  helpdesk_motive/pyproject.toml
  helpdesk_motive/readme/CONFIGURE.md
  helpdesk_motive/readme/CONTRIBUTORS.md
  helpdesk_motive/readme/DESCRIPTION.md
  helpdesk_motive/readme/USAGE.md
  helpdesk_motive/security/ir.model.access.csv
  helpdesk_motive/static/description/icon.png
  helpdesk_motive/static/description/index.html
  helpdesk_motive/tests/__init__.py
  helpdesk_motive/tests/test_helpdesk_motive.py
  helpdesk_motive/views/helpdesk_ticket.xml
  helpdesk_motive/views/helpdesk_ticket_motive.xml
  helpdesk_motive/views/helpdesk_ticket_team.xml
Labels: approved, ready to merge, bot is merging ⏳

#748 [17.0][IMP] helpdesk_mgmt: Add fold field to stage form view
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
Labels: approved, bot is merging ⏳

#749 [18.0][IMP] helpdesk_mgmt: Add fold field to stage form view
  helpdesk_mgmt/views/helpdesk_ticket_stage_views.xml
Labels: approved, bot is merging ⏳
