Repository OCA/helpdesk, pull requests merged in 2025-04, with the labels that each got.

#661 [17.0] [MIG] helpdesk_mgmt_stage_validation: Migration to 17.0
  helpdesk_mgmt_stage_validation/README.rst
  helpdesk_mgmt_stage_validation/__init__.py
  helpdesk_mgmt_stage_validation/__manifest__.py
  helpdesk_mgmt_stage_validation/i18n/helpdesk_mgmt_stage_validation.pot
  helpdesk_mgmt_stage_validation/i18n/it.po
  helpdesk_mgmt_stage_validation/models/__init__.py
  helpdesk_mgmt_stage_validation/models/helpdesk_ticket.py
  helpdesk_mgmt_stage_validation/models/helpdesk_ticket_stage.py
  helpdesk_mgmt_stage_validation/pyproject.toml
  helpdesk_mgmt_stage_validation/readme/CONFIGURE.md
  helpdesk_mgmt_stage_validation/readme/CONTRIBUTORS.md
  helpdesk_mgmt_stage_validation/readme/DESCRIPTION.md
  helpdesk_mgmt_stage_validation/readme/USAGE.md
  helpdesk_mgmt_stage_validation/static/description/icon.png
  helpdesk_mgmt_stage_validation/static/description/index.html
  helpdesk_mgmt_stage_validation/tests/__init__.py
  helpdesk_mgmt_stage_validation/tests/test_helpdesk_ticket_stage_validation.py
  helpdesk_mgmt_stage_validation/views/helpdesk_ticket_stage.xml
Labels: approved, bot is merging ⏳, stale

#706 [16.0][ADD] helpdesk_timesheet_time_type: New module helpdesk_timeshe…
  helpdesk_timesheet_time_type/README.rst
  helpdesk_timesheet_time_type/__init__.py
  helpdesk_timesheet_time_type/__manifest__.py
  helpdesk_timesheet_time_type/readme/CONTRIBUTORS.md
  helpdesk_timesheet_time_type/readme/DESCRIPTION.md
  helpdesk_timesheet_time_type/static/description/icon.png
  helpdesk_timesheet_time_type/static/description/icon.svg
  helpdesk_timesheet_time_type/static/description/index.html
  helpdesk_timesheet_time_type/views/helpdesk_ticket_view.xml
  setup/helpdesk_timesheet_time_type/odoo/addons/helpdesk_timesheet_time_type
  setup/helpdesk_timesheet_time_type/setup.py
Labels: approved, ready to merge, merged 🎉

#663 [17.0][IMP]helpdesk_mgmt: better attachment support
  helpdesk_mgmt/controllers/main.py
  helpdesk_mgmt/controllers/myaccount.py
  helpdesk_mgmt/tests/test_helpdesk_portal.py
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#701 [18.0][MIG] helpdesk_mgmt_sale: Migration to 18.0
  helpdesk_mgmt_sale/README.rst
  helpdesk_mgmt_sale/__init__.py
  helpdesk_mgmt_sale/__manifest__.py
  helpdesk_mgmt_sale/i18n/es.po
  helpdesk_mgmt_sale/i18n/helpdesk_mgmt_sale.pot
  helpdesk_mgmt_sale/i18n/it.po
  helpdesk_mgmt_sale/models/__init__.py
  helpdesk_mgmt_sale/models/helpdesk_ticket.py
  helpdesk_mgmt_sale/models/sale_order.py
  helpdesk_mgmt_sale/pyproject.toml
  helpdesk_mgmt_sale/readme/CONTRIBUTORS.md
  helpdesk_mgmt_sale/readme/DESCRIPTION.md
  helpdesk_mgmt_sale/readme/USAGE.md
  helpdesk_mgmt_sale/static/description/icon.png
  helpdesk_mgmt_sale/static/description/icon.svg
  helpdesk_mgmt_sale/static/description/index.html
  helpdesk_mgmt_sale/tests/__init__.py
  helpdesk_mgmt_sale/tests/test_helpdesk_ticket.py
  helpdesk_mgmt_sale/views/helpdesk_ticket_views.xml
  helpdesk_mgmt_sale/views/sale_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#710 [16.0][IMP] helpdesk_mgmt_timesheet: fix keyerror 'active_model'
  helpdesk_mgmt_timesheet/wizards/hr_timesheet_switch.py
Labels: approved, bot is merging ⏳

#712 [17.0][MIG] helpdesk_type: Migration to version 17.0
  helpdesk_type/README.rst
  helpdesk_type/__init__.py
  helpdesk_type/__manifest__.py
  helpdesk_type/demo/helpdesk_type_demo.xml
  helpdesk_type/i18n/es.po
  helpdesk_type/i18n/es_AR.po
  helpdesk_type/i18n/fr.po
  helpdesk_type/i18n/helpdesk_type.pot
  helpdesk_type/i18n/it.po
  helpdesk_type/i18n/pt.po
  helpdesk_type/i18n/pt_BR.po
  helpdesk_type/i18n/sv.po
  helpdesk_type/models/__init__.py
  helpdesk_type/models/helpdesk_ticket.py
  helpdesk_type/models/helpdesk_ticket_team.py
  helpdesk_type/models/helpdesk_ticket_type.py
  helpdesk_type/pyproject.toml
  helpdesk_type/readme/CONFIGURE.md
  helpdesk_type/readme/CONTRIBUTORS.md
  helpdesk_type/readme/DESCRIPTION.md
  helpdesk_type/readme/USAGE.md
  helpdesk_type/security/ir.model.access.csv
  helpdesk_type/static/description/icon.png
  helpdesk_type/static/description/index.html
  helpdesk_type/tests/__init__.py
  helpdesk_type/tests/test_helpdesk_type.py
  helpdesk_type/views/helpdesk_ticket.xml
  helpdesk_type/views/helpdesk_ticket_team.xml
  helpdesk_type/views/helpdesk_ticket_type.xml
Labels: approved, bot is merging ⏳

#713 [17.0][MIG] helpdesk_ticket_open_tab: Migration to 17.0
  helpdesk_ticket_open_tab/README.rst
  helpdesk_ticket_open_tab/__init__.py
  helpdesk_ticket_open_tab/__manifest__.py
  helpdesk_ticket_open_tab/i18n/.empty
  helpdesk_ticket_open_tab/i18n/helpdesk_ticket_open_tab.pot
  helpdesk_ticket_open_tab/i18n/it.po
  helpdesk_ticket_open_tab/pyproject.toml
  helpdesk_ticket_open_tab/readme/CONTRIBUTORS.md
  helpdesk_ticket_open_tab/readme/DESCRIPTION.md
  helpdesk_ticket_open_tab/readme/USAGE.md
  helpdesk_ticket_open_tab/static/description/icon.png
  helpdesk_ticket_open_tab/static/description/index.html
  helpdesk_ticket_open_tab/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#715 [17.0][MIG] helpdesk_ticket_related: Migration to 17.0
  helpdesk_ticket_related/README.rst
  helpdesk_ticket_related/__init__.py
  helpdesk_ticket_related/__manifest__.py
  helpdesk_ticket_related/i18n/ca.po
  helpdesk_ticket_related/i18n/es.po
  helpdesk_ticket_related/i18n/helpdesk_ticket_related.pot
  helpdesk_ticket_related/i18n/it.po
  helpdesk_ticket_related/i18n/sv.po
  helpdesk_ticket_related/models/__init__.py
  helpdesk_ticket_related/models/helpdesk_ticket.py
  helpdesk_ticket_related/pyproject.toml
  helpdesk_ticket_related/readme/CONTRIBUTORS.md
  helpdesk_ticket_related/readme/DESCRIPTION.md
  helpdesk_ticket_related/static/description/icon.png
  helpdesk_ticket_related/static/description/icon.svg
  helpdesk_ticket_related/static/description/index.html
  helpdesk_ticket_related/tests/__init__.py
  helpdesk_ticket_related/tests/test_related_tickets.py
  helpdesk_ticket_related/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#717 [17.0][MIG] helpdesk_portal_restriction: Migration to 17.0
  helpdesk_portal_restriction/README.rst
  helpdesk_portal_restriction/__init__.py
  helpdesk_portal_restriction/__manifest__.py
  helpdesk_portal_restriction/controllers/__init__.py
  helpdesk_portal_restriction/controllers/main.py
  helpdesk_portal_restriction/i18n/helpdesk_portal_restriction.pot
  helpdesk_portal_restriction/i18n/it.po
  helpdesk_portal_restriction/models/__init__.py
  helpdesk_portal_restriction/models/helpdesk_ticket_category.py
  helpdesk_portal_restriction/models/helpdesk_ticket_team.py
  helpdesk_portal_restriction/models/res_partner.py
  helpdesk_portal_restriction/pyproject.toml
  helpdesk_portal_restriction/readme/CONTRIBUTORS.md
  helpdesk_portal_restriction/readme/DESCRIPTION.md
  helpdesk_portal_restriction/readme/USAGE.md
  helpdesk_portal_restriction/static/description/icon.png
  helpdesk_portal_restriction/static/description/icon.svg
  helpdesk_portal_restriction/static/description/index.html
  helpdesk_portal_restriction/views/res_partner.xml
Labels: approved, bot is merging ⏳

#716 [17.0][MIG] helpdesk_mgmt_portal_follower: Migration to 17.0
  helpdesk_mgmt_portal_follower/README.rst
  helpdesk_mgmt_portal_follower/__init__.py
  helpdesk_mgmt_portal_follower/__manifest__.py
  helpdesk_mgmt_portal_follower/controllers/__init__.py
  helpdesk_mgmt_portal_follower/controllers/main.py
  helpdesk_mgmt_portal_follower/i18n/es.po
  helpdesk_mgmt_portal_follower/i18n/helpdesk_mgmt_portal_follower.pot
  helpdesk_mgmt_portal_follower/i18n/it.po
  helpdesk_mgmt_portal_follower/i18n/pt_BR.po
  helpdesk_mgmt_portal_follower/pyproject.toml
  helpdesk_mgmt_portal_follower/readme/CONTRIBUTORS.md
  helpdesk_mgmt_portal_follower/readme/DESCRIPTION.md
  helpdesk_mgmt_portal_follower/readme/ROADMAP.md
  helpdesk_mgmt_portal_follower/readme/USAGE.md
  helpdesk_mgmt_portal_follower/static/description/icon.png
  helpdesk_mgmt_portal_follower/static/description/index.html
  helpdesk_mgmt_portal_follower/tests/__init__.py
  helpdesk_mgmt_portal_follower/tests/test_ticket_followers.py
  helpdesk_mgmt_portal_follower/views/helpdesk_templates.xml
Labels: approved, bot is merging ⏳

#719 [16.0][FIX] helpdesk_mgmt_portal_follower: Fixed manifest maintainers key
  helpdesk_mgmt_portal_follower/README.rst
  helpdesk_mgmt_portal_follower/__manifest__.py
  helpdesk_mgmt_portal_follower/static/description/index.html
Labels: approved, bot is merging ⏳

#695 [17.0][MIG] helpdesk_mgmt_timesheet: Migration to 17.0
  helpdesk_mgmt_timesheet/README.rst
  helpdesk_mgmt_timesheet/__init__.py
  helpdesk_mgmt_timesheet/__manifest__.py
  helpdesk_mgmt_timesheet/controllers/__init__.py
  helpdesk_mgmt_timesheet/controllers/main.py
  helpdesk_mgmt_timesheet/demo/helpdesk_mgmt_timesheet_demo.xml
  helpdesk_mgmt_timesheet/i18n/es.po
  helpdesk_mgmt_timesheet/i18n/es_AR.po
  helpdesk_mgmt_timesheet/i18n/fr.po
  helpdesk_mgmt_timesheet/i18n/helpdesk_mgmt_timesheet.pot
  helpdesk_mgmt_timesheet/i18n/hu.po
  helpdesk_mgmt_timesheet/i18n/it.po
  helpdesk_mgmt_timesheet/i18n/pt.po
  helpdesk_mgmt_timesheet/i18n/pt_BR.po
  helpdesk_mgmt_timesheet/i18n/sv.po
  helpdesk_mgmt_timesheet/models/__init__.py
  helpdesk_mgmt_timesheet/models/helpdesk_ticket.py
  helpdesk_mgmt_timesheet/models/helpdesk_ticket_team.py
  helpdesk_mgmt_timesheet/models/hr_timesheet.py
  helpdesk_mgmt_timesheet/pyproject.toml
  helpdesk_mgmt_timesheet/readme/CONFIGURE.md
  helpdesk_mgmt_timesheet/readme/CONTRIBUTORS.md
  helpdesk_mgmt_timesheet/readme/DESCRIPTION.md
  helpdesk_mgmt_timesheet/readme/USAGE.md
  helpdesk_mgmt_timesheet/report/report_timesheet_templates.xml
  helpdesk_mgmt_timesheet/static/description/icon.png
  helpdesk_mgmt_timesheet/static/description/index.html
  helpdesk_mgmt_timesheet/tests/__init__.py
  helpdesk_mgmt_timesheet/tests/test_helpdesk_mgmt_timesheet.py
  helpdesk_mgmt_timesheet/tests/test_helpdesk_portal.py
  helpdesk_mgmt_timesheet/tests/test_helpdesk_timesheet_time_control.py
  helpdesk_mgmt_timesheet/views/helpdesk_project_task_view.xml
  helpdesk_mgmt_timesheet/views/helpdesk_team_view.xml
  helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
  helpdesk_mgmt_timesheet/views/hr_timesheet_view.xml
  helpdesk_mgmt_timesheet/wizards/__init__.py
  helpdesk_mgmt_timesheet/wizards/hr_timesheet_switch.py
Labels: approved, ready to merge, bot is merging ⏳

#721 [17.0][MIG] helpdesk_timesheet_time_type: Migration to 17.0
  helpdesk_timesheet_time_type/README.rst
  helpdesk_timesheet_time_type/__init__.py
  helpdesk_timesheet_time_type/__manifest__.py
  helpdesk_timesheet_time_type/i18n/helpdesk_timesheet_time_type.pot
  helpdesk_timesheet_time_type/i18n/it.po
  helpdesk_timesheet_time_type/pyproject.toml
  helpdesk_timesheet_time_type/readme/CONTRIBUTORS.md
  helpdesk_timesheet_time_type/readme/DESCRIPTION.md
  helpdesk_timesheet_time_type/static/description/icon.png
  helpdesk_timesheet_time_type/static/description/icon.svg
  helpdesk_timesheet_time_type/static/description/index.html
  helpdesk_timesheet_time_type/views/helpdesk_ticket_view.xml
Labels: approved, bot is merging ⏳

#709 [16.0][IMP] helpdesk_ticket_close_inactive: Modified category functionality
  helpdesk_ticket_close_inactive/README.rst
  helpdesk_ticket_close_inactive/models/helpdesk_ticket_team.py
  helpdesk_ticket_close_inactive/readme/CONTRIBUTORS.md
  helpdesk_ticket_close_inactive/static/description/index.html
  helpdesk_ticket_close_inactive/tests/test_ticket_autoclose.py
  helpdesk_ticket_close_inactive/views/helpdesk_ticket_team.xml
Labels: approved, ready to merge, bot is merging ⏳

#724 [17.0][IMP] helpdesk_mgmt: Reposition 'New Ticket' Button
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳

#726 [17.0][IMP] helpdesk_mgmt: Adapting portal ticket design to odoo style
  helpdesk_mgmt/static/src/img/helpdesk_icon.svg
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳

#729 [17.0][FIX] helpdesk_mgmt: Fix user_id when new ticket is created
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: approved, bot is merging ⏳

#732 [17.0][IMP] helpdesk_mgmt: Add stage time tracking to helpdesk tickets
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#731 [17.0][FIX] helpdesk_mgmt_timesheet: Fix error when see timesheets reports
  helpdesk_mgmt_timesheet/README.rst
  helpdesk_mgmt_timesheet/__init__.py
  helpdesk_mgmt_timesheet/readme/CONTRIBUTORS.md
  helpdesk_mgmt_timesheet/report/__init__.py
  helpdesk_mgmt_timesheet/report/timesheets_analysis_report.py
  helpdesk_mgmt_timesheet/static/description/index.html
Labels: approved, bot is merging ⏳

#734 [18.0][IMP]helpdesk_mgmt: helpdesk_mgmt: Add stage time tracking to helpdesk tickets
  helpdesk_mgmt/models/helpdesk_ticket.py
  helpdesk_mgmt/views/helpdesk_ticket_views.xml
Labels: approved, bot is merging ⏳

#725 [17.0][IMP] helpdesk_type: Portal ticket type
  helpdesk_mgmt/i18n/es.po
  helpdesk_mgmt/i18n/helpdesk_mgmt.pot
  helpdesk_mgmt/views/res_config_settings_views.xml
  helpdesk_type/README.rst
  helpdesk_type/__init__.py
  helpdesk_type/__manifest__.py
  helpdesk_type/controllers/__init__.py
  helpdesk_type/controllers/main.py
  helpdesk_type/i18n/es.po
  helpdesk_type/i18n/helpdesk_type.pot
  helpdesk_type/models/__init__.py
  helpdesk_type/models/helpdesk_ticket_type.py
  helpdesk_type/models/res_company.py
  helpdesk_type/models/res_config_settings.py
  helpdesk_type/readme/CONTRIBUTORS.md
  helpdesk_type/security/ir.model.access.csv
  helpdesk_type/static/description/index.html
  helpdesk_type/views/helpdesk_ticket_templates.xml
  helpdesk_type/views/res_config_settings_views.xml
Labels: approved

#737 [18.0][FIX] helpdesk_mgmt: Fix user_id when new ticket is created
  helpdesk_mgmt/models/helpdesk_ticket.py
Labels: bot is merging ⏳

#735 [18.0][FIX] helpdesk_mgmt: Embed "New Ticket" portal button properly
  helpdesk_mgmt/views/helpdesk_ticket_templates.xml
Labels: approved, bot is merging ⏳
